name: Deploy to PythonAnywhere

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install HTTPie
      run: pip install httpie

    - name: Deploy to PythonAnywhere
      env:
        PA_USERNAME: ${{ secrets.PA_USERNAME }}
        PA_API_TOKEN: ${{ secrets.PA_API_TOKEN }}
      run: |
        http --form POST https://www.pythonanywhere.com/api/v0/user/$PA_USERNAME/webapps/yourusername.pythonanywhere.com/reload/ \
        Authorization:"Token $PA_API_TOKEN"
