name: Deploy to PythonAnywhere

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install PythonAnywhere CLI
        run: pip install --upgrade pythonanywhere-cli

      - name: Upload to PythonAnywhere
        run: |
          python -m pythonanywhere.deploy \
            --username "${{ secrets.PA_USERNAME }}" \
            --api_token "${{ secrets.PA_API_TOKEN }}" \
            --path . \
            --target /home/orderd/mysite \
            --domain orderd.pythonanywhere.com
