name: Deploy to PythonAnywhere

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Clone repo
      uses: actions/checkout@v3

    - name: Upload to PythonAnywhere
      run: |
        pip install pythonanywhere
        python -m pythonanywhere.deploy \
          --username ${{ secrets.PA_USERNAME }} \
          --api_token ${{ secrets.PA_API_TOKEN }} \
          --path . \
          --target /home/orderd/mysite \
          --domain orderd.pythonanywhere.com
